site_name: argparse
site_url: http://localhost:8080
theme: readthedocs

plugins:
  - search:
      indexing: 'sections'

nav:
  - Home: 'index.md'
  - Getting Started:
    - Quick Start: 'getting_started/quick_start.md'
  - Legal:
    - Project License: 'legal/license.md'